name: applicationstugo
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  intl_phone_field: ^3.2.0
  device_preview: ^1.1.0
  image_picker: ^1.0.4
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  country_picker: ^2.0.23
  intl: ^0.18.1
  email_validator: ^2.1.17
  firebase_storage: ^11.6.0
  shared_preferences: ^2.2.2
  latlong2: ^0.9.0
  location: ^5.0.3
  geocoding: ^2.1.1
  emailjs: ^1.3.0
  flutter_secure_storage: ^9.0.0
  google_maps_flutter: ^2.5.3
  google_maps_place_picker_mb: ^3.1.2
  flutter_bloc: ^8.0.0
  flutter_spinkit: ^5.1.0
  flutter_lints: ^2.0.0

  booking_calendar: ^1.1.10
  url_launcher: ^6.2.4
  animated_rating_stars: ^1.0.1
  fl_chart: ^0.67.0
  uuid: ^4.4.0
  flutter_dotenv: ^5.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - .env
    - images/Fixing AC.jpg
    - images/logo.png
    - images/BackButton.png
    - images/PP.jpg
    - images/icons8-question-mark-48.png
    - images/Alpacino.jpg
    - images/avatar-default-symbolic.240x256.png
    - images/test.jpg
    - images/pp.png
    - images/default avatar.png
    - images/cameraicon.png
    - images/share and earn.png
    - images/register as partner.png
    - images/rate us.png
    - images/privacy policy.png
    - images/My booking.png
    - images/help center.png
    - images/FAQ'S.png
    - images/Logout.png
    - images/search icon nav.png
    - images/Profile icon nav.png
    - images/home icon nav.png
    - images/booking icon nav.png
    - images/active home icon.png
    - images/active booking icon.png
    - images/active profile icon.png
    - images/active search icon.png
    - images/blck background.png
    - images/parnter nexticon.png
    - images/foot massage.jpg
    - images/loicon.png
    - images/down arrow.png
    - images/notifications icon.png
    - images/searchbar.png
    - images/bathroom cleaning.jpg
    - images/carcleaning.jpg
    - images/pest control.jpg
    - images/Ac services.png
    - images/appliances.png
    - images/cleaning.png
    - images/electrical.png
    - images/home assist.png
    - images/More.png
    - images/painint.png
    - images/pest control icon.png
    - images/right arrows.png
    - images/barber.jpg
    - images/home cleanning.jpeg
    - images/massage.jpeg
    - images/man massgae.jpg
    - images/trimming hair.jpg
    - images/dashboardiconinactive.png
    - images/dashboardiconactive.png
    - images/Earningsiconinactive.png
    - images/Earningsiconactive.png
    - images/nned a service.png
    - images/offer a service.png
    - images/man.png
    - images/female.png
    - images/right-arrow.png
    - images/new calender.gif
    - images/calendar-7-48.png
    - images/close.png
    - images/male1.png
    - images/female1.png
    - images/Plumber.jpeg
    - images/painting.jpeg
    - images/Electrician.jpeg
    - images/Carpenter.jpeg
    - images/AC Services.jpeg
    - images/next_arrow.png
    - images/location (1).png
    - images/Phone.png
    - images/blank_img.png
    - images/blank_booking.png
    - images/star_filled.png
    - images/star_unfilled.png
    - images/visa.png
    - images/gpay.png
    - images/cash.png
    - images/failedPayment.png
    - images/confirmPayment.png
    - images/doublerightarrow.png
    - images/googlemaps.png
    - images/Google_maps.png
    - images/comingsoon.png
    - images/shareandearn.png
    - images/Appliancesmore.png
    - images/homeassistmore.png


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf

    #         style: italic
    - family: ArchivoBlack
      fonts:
        - asset: fonts/ArchivoBlack-Regular.ttf
        - asset: fonts/OpenSans-Regular.ttf
  #         weight: 700
  #
